import { PricingPlan } from "@/types";

export const PACK_CREDITS: Record<"starter" | "explorer" | "founder", number> = {
  starter: 5,
  explorer: 15,
  founder: 50,
};

export const pricingPlans: PricingPlan[] = [
  {
    name: "Free",
    planId: "free",
    price: "$0",
    description: "Perfect to test the radar's power.",
    credits: 2,
    features: [
      "2 credits included at signup",
      "Basic pain point detection",
      "Opportunity scoring",
    ],
    cta: "Start Discovering (Free)",
  },
  {
    name: "Starter",
    planId: "starter",
    price: "$9",
    badge: "one-time",
    description: "Launch your first product ideas.",
    credits: 5,
    features: [
      "5 full analysis credits",
      "AI-ready prompt generated",
      "Product ideas & MVP",
      "SEO keyword suggestions",
      "Targeted acquisition channels",
      "Export data (PDF / JSON)",
      "Credits never expire",
    ],
    cta: "Get 5 Credits",
  },
  {
    name: "Explorer",
    planId: "explorer",
    price: "$19",
    badge: "most popular",
    description: "Explore multiple niches and validate faster.",
    credits: 15,
    features: [
      "15 full analysis credits",
      "AI-ready prompt generated",
      "Product ideas & MVP",
      "SEO keyword suggestions",
      "Targeted acquisition channels",
      "Export data (PDF / JSON)",
      "Priority email support",
      "Credits never expire",
    ],
    cta: "Get 15 Credits",
    highlighted: true,
  },
  {
    name: "Founder",
    planId: "founder",
    price: "$49",
    badge: "best value",
    description: "For serious founders validating multiple ideas.",
    credits: 50,
    features: [
      "50 full analysis credits",
      "AI-ready prompt generated",
      "Product ideas & MVP",
      "SEO keyword suggestions",
      "Targeted acquisition channels",
      "Export data (PDF / JSON)",
      "Priority access to new features",
      "Dedicated support channel",
      "Credits never expire",
    ],
    cta: "Get 50 Credits",
  },
];
